// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.Models.Context;

namespace MyApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191005183957_sunny")]
    partial class sunny
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyApp.Models.Category", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("categoryName")
                        .HasMaxLength(30);

                    b.Property<string>("description");

                    b.HasKey("categoryId");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("MyApp.Models.drinks", b =>
                {
                    b.Property<int>("drinkId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<string>("DetailDescription");

                    b.Property<string>("Photo")
                        .IsRequired();

                    b.Property<string>("drinkName")
                        .HasMaxLength(30);

                    b.Property<bool>("inStock");

                    b.Property<int>("price");

                    b.Property<string>("shortDescription")
                        .HasMaxLength(100);

                    b.Property<int>("storage");

                    b.Property<string>("thumbnail");

                    b.HasKey("drinkId");

                    b.HasIndex("CategoryId");

                    b.ToTable("drinks");
                });

            modelBuilder.Entity("MyApp.Models.drinks", b =>
                {
                    b.HasOne("MyApp.Models.Category", "Category")
                        .WithMany("drinks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
